### ISSUE TITLE
Error when next spawn.

### ISSUE THREAD

**Issue by chaixshot** [Sighmir/vrp_home_spawn#1]
Sending heartbeat to live-internal.fivem.net:30110
Error running system event handling function for resource vrp: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: [string "-- Proxy interface system, used to add/call f..."]:39: bad argument #1 to 'unpack' (table expected, got number)
stack traceback:
        [C]: in function 'table.unpack'
        [string "-- Proxy interface system, used to add/call f..."]:39: in upvalue 'handler'
        citizen:/scripting/lua/scheduler.lua:175: in function <citizen:/scripting/lua/scheduler.lua:174>
stack traceback:
        [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:174: in function <citizen:/scripting/lua/scheduler.lua:138>
        [C]: in function 'coroutine.resume'
        citizen:/scripting/lua/scheduler.lua:115: in function <citizen:/scripting/lua/scheduler.lua:100>
Sending heartbeat to live-internal.fivem.net:30110

**Comment by Sighmir** [comment]
That error doesn't seem to be related to any files on the script, are you using vRPex? Please attach your CitizenFX.log for the server on the next comment. :smile:

**Comment by Sighmir** [comment]
That error doesn't seem to be related to any files on the script, are you using vRPex? Please attach your CitizenFX.log for the server on the next comment. :smile:

**Comment by chaixshot** [comment]
On vrp - https://github.com/ImagicTheCat/vRP
https://drive.google.com/open?id=1ijlZbLnAA9Nu-vhK7r48IOnWRnwy-lvC

**Comment by Sighmir** [comment]
I can't access the file.

**Comment by chaixshot** [comment]
i'm done

**Comment by Sighmir** [comment]
I can now.

**Comment by Sighmir** [comment]
The CitizenFX.log file has to have information about the issue I am trying to solve, I can't find the resource vrp_home_spawn being started anywhere in that file. Please reproduce your issue and then send me the log.

**Comment by chaixshot** [comment]
update
https://drive.google.com/open?id=1ijlZbLnAA9Nu-vhK7r48IOnWRnwy-lvC

**Comment by chaixshot** [comment]
When test, your  have problem?

**Comment by Sighmir** [comment]
Your issue is that this script was updated to vRPex and doesn't support vRP anymore. It's vRPex only.
